// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfF9EPgQDIzim5uOsJbGcboHJn-kT1B0',
    appId: '1:957926978125:android:81b80e68c16bb019596204',
    messagingSenderId: '957926978125',
    projectId: 'find-my-doc-app',
    storageBucket: 'find-my-doc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEXVu8VP3-KAbBonGKwZacX71Mw72QXE',
    appId: '1:957926978125:ios:b01e875556399df4596204',
    messagingSenderId: '957926978125',
    projectId: 'find-my-doc-app',
    storageBucket: 'find-my-doc-app.appspot.com',
    androidClientId: '957926978125-iaeojr7ukcobindq33qgpdbf6tjcjalv.apps.googleusercontent.com',
    iosClientId: '957926978125-kop5615q04ulal5308qm7fj7v050qspj.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmydocUserFrontend',
  );
}
